name: "Package.json Version Bump Action"
description: "Automatically bumps versions and updates dependencies in a monorepo or single-package repo using Conventional Commits."
author: "bahulneel"
inputs:
  commit-template:
    description: "Commit message template for version bumps."
    required: false
    default: "chore(release): bump ${package} to ${version} (${bumpType})"
  dependency-commit-template:
    description: "Commit message template for dependency updates."
    required: false
    default: "chore(deps): update ${depPackage} to ${depVersion} in ${package} (patch)"
  create-branch:
    description: "Create a separate branch for version updates."
    required: false
    default: "false"
  branch-template:
    description: "Template for the branch name when creating branches."
    required: false
    default: "release/${version}"
  branch-cleanup:
    description: "Strategy for cleaning up versioned branches: 'keep' (keep all), 'prune' (keep latest only), or 'semantic' (keep same bump type only)."
    required: false
    default: "keep"
  target-branch:
    description: "The target branch to compare commits against."
    required: false
    default: "main"
  strategy:
    description: "Strategy for same-type incremental changes: 'do-nothing' (skip), 'apply-bump' (normal semver), or 'pre-release' (use prerelease versions)."
    required: false
    default: "do-nothing"
  source-branch:
    description: "Source branch for detecting target branch updates and prerelease finalization."
    required: false
    default: "develop"
  tag-prereleases:
    description: "Create git tags for prerelease versions."
    required: false
    default: "false"
outputs:
  branch:
    description: "The branch that was created or updated."
runs:
  using: "node20"
  main: "dist/index.cjs"
branding:
  icon: "git-commit"
  color: "blue"
