name: "Package.json Version Bump Action"
description: "Automatically bumps versions and updates dependencies in a monorepo or single-package repo using Conventional Commits."
author: "bahulneel"
inputs:
  commit_message_template:
    description: "Commit message template for version bumps."
    required: false
    default: "chore(release): bump ${package} to ${version} (${bumpType})"
  dep_commit_message_template:
    description: "Commit message template for dependency updates."
    required: false
    default: "chore(deps): update ${depPackage} to ${depVersion} in ${package} (patch)"
  branch:
    description: "Update versions is a seperated branch."
    required: false
    default: ?0
  branch_template:
    description: "Template for the branch to push to."
    required: false
    default: "release/${version}"
  branch_deletion:
    description: "Strategy for keeping the number of versioned branches. 'keep' will keep all versioned branches, 'prune' will prune all versioned branches except the latest one, 'semantic' will prune all verions branches of the same bump type."
    required: false
    default: "keep"
outputs:
  branch:
    description: "The branch that was created or updated."
runs:
  using: "node20"
  main: "dist/index.cjs"
branding:
  icon: "git-commit"
  color: "blue"
