name: "Monorepo Version Bump Action"
description: "Automatically bumps versions and updates dependencies in a monorepo or single-package repo using Conventional Commits."
author: "bahulneel"
inputs:
  commit_message_template:
    description: "Commit message template for version bumps."
    required: false
    default: "chore(release): bump ${package} to ${version} (${bumpType})"
  dep_commit_message_template:
    description: "Commit message template for dependency updates."
    required: false
    default: "chore(deps): update ${depPackage} to ${depVersion} in ${package} (patch)"
  tag_version:
    description: "Whether to tag the version."
    required: false
    default: "false"
runs:
  using: "node20"
  main: "dist/index.cjs"
branding:
  icon: "git-commit"
  color: "blue"
