name: Package.json Version Bump Action
description: Automatically bumps versions and updates dependencies in a monorepo or single-package repo using Conventional Commits.
author: bahulneel
inputs:
  commit_template:
    description: Commit message template for version bumps.
    required: false
    default: "chore(release): bump ${package} to ${version} (${bumpType})"
  dependency_commit_template:
    description: Commit message template for dependency updates.
    required: false
    default: "chore(deps): update ${depPackage} to ${depVersion} in ${package} (patch)"
  commit_format:
    description: "Commit format strategy: 'template' (use templates) or 'conventional' (use conventional commit format)."
    required: false
    default: "conventional"
  create_branch:
    description: Create a separate branch for version updates.
    required: false
    default: "false"
  branch_template:
    description: Template for the branch name when creating branches.
    required: false
    default: "release/${version}"
  branch_cleanup:
    description: "Strategy for cleaning up versioned branches: 'keep' (keep all), 'prune' (keep latest only), or 'semantic' (keep same bump type only)."
    required: false
    default: keep
  base:
    description: The base branch to compare commits against.
    required: false
    default: main
  strategy:
    description: "Strategy for same-type incremental changes: 'do-nothing' (skip), 'apply-bump' (normal semver), or 'pre-release' (use prerelease versions)."
    required: false
    default: do-nothing
  branch:
    description: Active branch for detecting base branch updates and prerelease finalization.
    required: false
    default: develop
  tag_prereleases:
    description: Create git tags for prerelease versions.
    required: false
    default: "false"
  release:
    description: "Release mode: Create a release branch by finalizing prerelease versions. When true, bypasses flow matching and forces: strategy=finalize, create_branch=true, branch_template=release/${version}. Use this for manual release creation."
    required: false
    default: "false"
  # Tactic-specific configuration
  tactic_mergebase_lookbackcommits:
    description: Number of commits to look back when finding merge base (MergeBase tactic). Must be a positive integer. Default 10 to handle merge commits.
    required: false
    default: "10"
  tactic_lastversioncommit_maxcount:
    description: Number of version commits to consider when finding last version change (LastVersionCommit tactic). Must be a positive integer.
    required: false
    default: "1"
outputs:
  branch:
    description: The branch that was created or updated.
  packages-updated:
    description: Number of packages that had their versions updated.
  releases-created:
    description: Number of release versions created.
  prereleases-created:
    description: Number of prerelease versions created.
  versions-finalized:
    description: Number of prerelease versions finalized to releases.
  test-failures:
    description: Number of packages that failed tests during updates.
  strategy-used:
    description: The strategy that was used for version bumping.
  changes-made:
    description: Boolean indicating if any changes were made.
runs:
  using: node20
  main: dist/index.cjs
branding:
  icon: git-commit
  color: blue
